PREFIX graph: <http://example.org#>
PREFIX vaem: <http://www.linkedmodel.org/schema/vaem#>
PREFIX qudt: <http://qudt.org/schema/qudt#>

select distinct ?gtin ?itemQuantity ?productSize ?productSizeUnit 
where{ 
    #item part
    ?item vaem:name "Broccoli".
    ?item graph:amount ?itemQuantity. 

    optional {
        #product part
        ?item graph:matches ?product. 
        ?product graph:gtin ?gtin.
        ?product qudt:hasQuantity ?productQuantity.
        ?productQuantity qudt:value ?productSize. 
        ?productQuantity qudt:unit ?productSizeUnit.
    }
}
